workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.myapp"  # kendi uygulama package adını yaz
      node: 16.20.0
      java: 17
    scripts:
      - npm install
      - cd android
      - ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - bayramcomp@gmail.com  # kendi mail adresini yaz
